---
type: map
mapping:
    # Global configuration of computing nodes.
    "images":
        type: map
        required: true
        mapping:
            "default":
                type: str
                required: true
            "=":
                type: str
    "network":
        type: str
        required: true
    "secgroups":
        type: seq
        required: true
        sequence:
            - type: str
    "sshkey":
        type: str
        required: true
    "pubkeys":
        type: seq
        sequence:
            - type: str
    "graceful":
        type: bool
        required: true
    # Inventory.
    "nodes_inventory":
        type: map
        matching-rule: all
        mapping:
            regex;([a-z][0-9].*):
                type: int
    # Resource group definitions.
    "deployment":
        type: map
        required: true
        mapping:
            "=":
                type: map
                mapping:
                    "count":
                        type: int
                        required: true
                        range:
                            min: 0
                    "flavor":
                        type: str
                        required: true
                        enum:
                          - xlarge
                          - xxlarge
                          - tiny
                          - small
                          - medium
                          - large
                          - 8cpu-32GB-20dsk
                          # Cineca
                          - fl.ada.xs
                          - fl.ada.s
                          - fl.ada.m
                          - fl.ada.l
                          - fl.ada.xl
                          - fl.ada.xxl
                          - fl.ada.full
                    "start":
                        type: date
                        required: false
                        format: "%Y-%m-%d"
                    "end":
                        type: date
                        required: false
                        format: "%Y-%m-%d"
                    "group":
                        type: str
                        required: true
                    "image":
                        type: str
                        required: false
                    "volume":
                        type: map
                        required: false
                        'mapping':
                            "size":
                                type: int
                                range:
                                    min: 12
                            "type":
                                type: str
                                enum:
                                    - default
                                    - netapp
                            "boot":
                                type: bool
                    "cgroups":
                        type: map
                        required: false
                        'mapping':
                            "mem_limit_policy":
                                type: str
                                enum:
                                    - soft
                                    - hard
                            "mem_reserved_size":
                                type: int
                                required: true
                                range:
                                    min: 1024
                    "docker":
                        type: bool
                        required: false
